image: alpine:latest

stages:
  - deploy

before_script:
  - apk add --no-cache openssh-client
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa

deploy:
  stage: deploy
  environment: production
  only:
    - main
    - triggers
  script:
    - |
      ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" << 'EOF'
        cd ~/reddit-deploy
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
        docker compose pull
        docker compose up -d
      EOF
