version: '3.8'

services:
  back:
    image: registry.gitlab.com/kawqe123123124/reddit-back:latest
    container_name: reddit_back
    env_file:
      - .env
    command:
      - bash -lc
      - |
        alembic upgrade head &&
        exec uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - appnet

  frontend:
    image: registry.gitlab.com/kawqe123123124/reddit-front:latest
    container_name: reddit_front
    ports:
      - "8080:80"
    depends_on:
      - back
    networks:
      - appnet

  db:
    image: postgres:16.3-alpine
    container_name: reddit_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

  redis:
    image: redis:7
    container_name: reddit_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - appnet

  celery:
    image: registry.gitlab.com/kawqe123123124/reddit-back:latest
    container_name: reddit_celery
    command: poetry run celery -A src.celery_app:celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - appnet

  nginx:
    image: nginx:1.25-alpine
    container_name: reddit_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/staticfiles
      - media_volume:/media
    ports:
      - "80:80"
    depends_on:
      - frontend
      - back
    networks:
      - appnet

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  appnet:
    driver: bridge
